http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api/v1"

  routers:
    base-router-redirect:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: frontend-service
      rule: Host(`{{ trim (env "DOMAIN_NAME") }}`)

    base-router:
      entryPoints:
        - websecure
      service: frontend-service
      rule: Host(`{{ trim (env "DOMAIN_NAME") }}`)

    api-router:
      entryPoints:
        - websecure
      service: backend-service
      rule: Host(`{{ trim (env "DOMAIN_NAME") }}`) && PathPrefix(`/api/v1`)
      middlewares:
        - strip-api-prefix

    ip-base-router-redirect:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: frontend-service
      rule: "!HostRegexp(`{host:.+}`)"
    
    ip-base-router:
      entryPoints:
        - websecure
      service: frontend-service
      rule: "!HostRegexp(`{host:.+}`)"

    ip-api-router:
      entryPoints:
        - websecure
      service: backend-service
      rule: "!HostRegexp(`{host:.+}`) && PathPrefix(`/api/v1`)"
      middlewares:
        - strip-api-prefix

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: {{ trim (env "FRONTEND_HOST") }}

    backend-service:
      loadBalancer:
        servers:
          - url: {{ trim (env "BACKEND_HOST") }}
