api:
  insecure: true
  dashboard: true

providers:
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      tls: {}

serversTransport:
  insecureSkipVerify: true
